Do not show disallowed permissions alert on create role
RedHatInsights/insights-rbac-ui pull request #1004
Opened 2022-01-06 15:27 UTC by fhlavac

Fixes: [RHCLOUD-17455](https://issues.redhat.com/browse/RHCLOUD-17455)

When going back in the wizard from the "copy" path with disallowed permissions to the first step and selecting "Create a role from scratch" the alert with disallowed permissions is not visible anymore.

@john-dupuy

2022-01-06 15:36 UTC, karelhala approved these changes

2022-01-06 16:27 UTC, john-dupuy requested changes
Testing this out locally, I am seeing that this breaks the feature. E.g. testing by copying the "Subscriptions administrator" role will actually select the subscriptions permissions now.

2022-01-07 15:58 UTC, fhlavac commented
@john-dupuy can I ask for more details? It seems to work on my side.

2022-01-07 16:25 UTC, john-dupuy approved these changes
Issues I were seeing was due to outdated dependencies. After reinstalling - everything is working as intended!

2022-01-07 16:44 UTC, merged