Add Provisioning application to MUA
RedHatInsights/insights-rbac-ui pull request #1507
Opened 2023-08-08 14:55 UTC by lzap

This is our counterpart to https://github.com/RedHatInsights/insights-rbac-ui/commit/e0f26082a75aa0cc84e9b4b2dc54de850fc6463d

I am not sure what I am doing, need help and careful review. Specifically, the path and the identifier - should it match to something?

2023-08-08 15:02 UTC, mshriver commented
Thanks @lzap, this should address HMS concerns for RHCLOUD-27181

2023-08-09 07:07 UTC, Hyperkid123 requested changes

2023-08-09 08:27 UTC, lzap commented on src/presentational-components/myUserAccess/bundles.js
> +      repositories: '/provisioning',
Oh that is a typo actually, let me fix that.

2023-08-09 08:28 UTC, lzap commented on src/presentational-components/myUserAccess/bundles.js
> +      repositories: '/provisioning',
Rebased.

2023-08-10 06:36 UTC, Hyperkid123 approved these changes

2023-08-10 06:36 UTC, merged