feat(rolestable): delete roles modal
RedHatInsights/insights-rbac-ui pull request #1696
Opened 2024-11-06 20:03 UTC by InsaneZein

### Description
This allows user to delete Roles. Currently deleting roles api doesn't exist so in the meantime, clicking "delete role" button will just spit out a console.log message. 

[RHCLOUD-32241](https://issues.redhat.com/browse/RHCLOUD-32241)

---

### Screenshots
![Screenshot from 2024-11-06 14-02-56](https://github.com/user-attachments/assets/6089d93f-c49b-45c9-b035-68a00e388f27)

### Checklist ☑️
- [ ] PR only fixes one issue or story 
- [ ] Change reviewed for extraneous code 
- [ ] UI best practices adhered to 
- [ ] Commits squashed and meaningfully named 
- [ ] All PR checks pass locally (build, lint, test, E2E)

##
- [ ] _(Optional) QE: Needs QE attention (OUIA changed, perceived impact to tests, no test coverage)_
- [ ] _(Optional) QE: Has been mentioned_
- [ ] _(Optional) UX: Needs UX attention (end user UX modified, missing designs)_
- [ ] _(Optional) UX: Has been mentioned_
##

2024-11-06 21:48 UTC, InsaneZein commented
I realized that sometimes selectedRole is undefined so the modal shows undefined instead of the role name.

2024-11-07 12:02 UTC, karelhala requested changes
Looks like some of the messages needs to be changed to role's messages. Also when I pulled the PR I found it's missing the toolbar actions which should allow to remove multiple roles.

2024-11-07 12:02 UTC, karelhala commented on src/smart-components/role/RolesTable.tsx
> +            isOpen={isDeleteModalOpen}
Based on the mocks the modal is missing checkbox
```suggestion
            isOpen={isDeleteModalOpen}
            withCheckbox
```

2024-11-07 12:06 UTC, karelhala commented
@InsaneZein I've checked the API and it has a delete role option https://console.redhat.com/docs/api/rbac/v1#operations-Role-deleteRole it should however be available only on custom roles. If the role is custom can be checked in role definition if `system = false`

2024-11-13 08:19 UTC, karelhala requested changes
The modal is using groups messages and looks like this:
![Screenshot 2024-11-13 at 9 17 04](https://github.com/user-attachments/assets/03c1227f-e968-448e-b8be-c214170f4db0)

But the messages should be:
@
![image-2024-09-09-12-24-18-530](https://github.com/user-attachments/assets/1f9b1558-ee8d-4f9a-9743-f8e79b5312ea)


The DataView is missing an action button to remove multiple roles. Also selecting single item selects the whole table.

2024-11-13 14:10 UTC, InsaneZein commented
Ah ok the task made it sound like this was just for deleting a singular Role. I can work on adding an action button to delete multiple roles in another PR.

2024-11-14 14:01 UTC, InsaneZein commented
/retest

2024-11-14 14:24 UTC, karelhala approved these changes

2024-11-14 14:24 UTC, merged