Validate role/group dscription length
RedHatInsights/insights-rbac-ui pull request #655
Opened 2021-01-26 13:46 UTC by PanSpagetka

https://issues.redhat.com/browse/RHCLOUD-9804

2021-01-26 14:06 UTC, john-dupuy requested changes
Checking this out locally I was able to verify that the name was checked and I was unable to click submit.

However, I enter in a really long name, RBAC will still crash -- I think because it is trying to make an API request to see if the name exists? If the text is over 150 characters, we shouldn't check that. 

I believe this is the behavior for groups, as I can't crash RBAC in a similar way when editing the name of a group.

2021-01-26 14:26 UTC, Hyperkid123 commented
> However, I enter in a really long name, RBAC will still crash -- I think because it is trying to make an API request to see if the name exists? If the text is over 150 characters, we shouldn't check that.

That would be the name async validation. We have to limit that aswell. Probably just don't trigger the call.

2021-01-26 14:33 UTC, PanSpagetka commented
After last commit it shouldn't fire request if group name is too long

2021-01-26 14:39 UTC, john-dupuy commented
@PanSpagetka ah, I meant we need to do that for roles, groups are already working properly!

2021-01-28 15:28 UTC, john-dupuy approved these changes
Testing out locally, I can no longer crash RBAC by putting in a long role name in the edit modal. Nice work @PanSpagetka :+1:

2021-01-28 15:30 UTC, Hyperkid123 commented on src/smart-components/role/add-role-new/schema.js
> +                  type: 'max-length',
Can you use the constant as in the edit group modal?

2021-02-01 10:54 UTC, merged